"""
Django settings for people_first project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from email.utils import formataddr
from pathlib import Path

from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Read from .env further down, alongside SECRET_KEY and DEBUG. The literal
# below only applies if that read is ever removed.
ALLOWED_HOSTS = []

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'featured_work',
    'gallery',
    'inquiry',
    'insight_category',
    'Podcast',
    'testimonial',
    'ventures',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'people_first.urls'
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'people_first.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Configured below with decouple support for sqlite3 and postgresql.


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration


SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", cast=bool)

# .env already carried ALLOWED_HOSTS, but nothing read it — the literal []
# above stood, which rejects every request as soon as DEBUG is off. Empty in
# DEBUG is fine (Django then allows localhost), so the default stays empty.
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())


DB_ENGINE = config("DB_ENGINE", default="sqlite3" if (BASE_DIR / "db.sqlite3").exists() else "postgresql")
if DB_ENGINE == "sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="people_first"),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="admin"),
            "HOST": config("DB_HOST", default="127.0.0.1"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }


# The MAIL_* names come from a Laravel-style .env. Django has its own names for
# the same things, so each one is translated here rather than left unread.

# MAIL_MAILER is Laravel's transport selector. Django expresses the same choice
# as a backend import path, so it is mapped. An explicit EMAIL_BACKEND is more
# specific and still wins; MAIL_MAILER only decides when EMAIL_BACKEND is unset.
MAILER_BACKENDS = {
    "smtp": "django.core.mail.backends.smtp.EmailBackend",
    # Laravel's "log" writes mail to the log; the console backend is the
    # closest equivalent and the usual choice for local development.
    "log": "django.core.mail.backends.console.EmailBackend",
    "file": "django.core.mail.backends.filebased.EmailBackend",
    # "array" keeps sent mail in memory instead of delivering it.
    "array": "django.core.mail.backends.locmem.EmailBackend",
    "null": "django.core.mail.backends.dummy.EmailBackend",
}
_mailer = config("MAIL_MAILER", default="smtp").strip().lower()
EMAIL_BACKEND = config("EMAIL_BACKEND", default=None) or MAILER_BACKENDS.get(
    _mailer, MAILER_BACKENDS["smtp"]
)

EMAIL_FILE_PATH = BASE_DIR.parent / ".local" / "emails"
EMAIL_TIMEOUT = 10

EMAIL_HOST = config("MAIL_HOST", default="localhost")
EMAIL_PORT = config("MAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("MAIL_USERNAME", default="")
EMAIL_HOST_PASSWORD = config("MAIL_PASSWORD", default="")

# Django refuses to start if both are true, so this is a three-way choice, not
# two flags. "ssl" previously fell through to neither being set, which silently
# sent over an unencrypted connection on what is normally port 465.
_encryption = config("MAIL_ENCRYPTION", default="tls").strip().lower()
EMAIL_USE_TLS = _encryption == "tls"
EMAIL_USE_SSL = _encryption == "ssl"

# MAIL_FROM_NAME is the display name shown to the recipient. Django has no
# separate setting for it: the name and address are one "Name <addr>" string,
# which formataddr quotes correctly when the name contains a comma or a quote.
EMAIL_FROM_ADDRESS = config("MAIL_FROM_ADDRESS", default="noreply@sakafat.local")
# decouple already strips surrounding quotes; this also handles a value that
# was quoted twice, e.g. MAIL_FROM_NAME='"PEOPLE FIRST"'.
EMAIL_FROM_NAME = config("MAIL_FROM_NAME", default="").strip().strip('"').strip("'")
DEFAULT_FROM_EMAIL = (
    formataddr((EMAIL_FROM_NAME, EMAIL_FROM_ADDRESS))
    if EMAIL_FROM_NAME
    else EMAIL_FROM_ADDRESS
)
# Error mail (Django's own) should come from the same identity.
SERVER_EMAIL = DEFAULT_FROM_EMAIL