# Generated by Django 6.1.1 on 2026-09-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessible description for screen readers and SEO. If left blank, title or caption is used.', max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption or notes about the photograph.'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Determines slide order in the coverflow carousel (0, 1, 2...).'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(help_text='Gallery photograph. Recommended portrait ratio ~0.59 (e.g. 400x675px or 1200x2025px). Images are centered and cropped cleanly by the coverflow carousel.', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this image from the public gallery without deleting it.'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for internal organization or fallback accessibility description.', max_length=255),
        ),
    ]
