# Generated by Django 6.1.1 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_work', '0002_remove_featuredwork_media_featuredwork_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredwork',
            name='bullets',
            field=models.JSONField(blank=True, default=list, help_text='Bullet points list. Enter one per line in admin. Used primarily on Block 2 (Tech Events).'),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='description',
            field=models.TextField(help_text='Summary description paragraph.'),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='metric_label',
            field=models.CharField(blank=True, help_text="Primary metric label (e.g. 'Increased Performance Rate' or 'management skills').", max_length=255),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='metric_value',
            field=models.CharField(blank=True, help_text="Primary metric value (e.g. '80%' for Block 1, '30%' for Block 2).", max_length=100),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='0 for Block 1 (Podcast: market strategy), 1 for Block 2 (Tech Events Management).'),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='secondary_metric_label',
            field=models.CharField(blank=True, help_text="Secondary metric label (e.g. 'have knowledge about market strategies.' or 'Productivity events all over Pakistan').", max_length=255),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='secondary_metric_value',
            field=models.CharField(blank=True, help_text="Secondary metric value on the overlapping card (e.g. '27%' or '45%').", max_length=100),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Block photo (.webp/.jpg/.png). Block 1 aspect is ~0.7 (portrait), Block 2 aspect is 0.8.', null=True, upload_to='featured-work/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='title',
            field=models.CharField(help_text="Block title/headline. Newlines create line breaks in the design (e.g. 'Tech Events\\nManagement.').", max_length=255),
        ),
        migrations.AlterField(
            model_name='featuredwork',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or video link.', null=True),
        ),
    ]
