# Generated by Django 6.1.1 on 2026-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_category', '0004_remove_insight_featured_remove_insight_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
