# Generated by Django 6.1.1 on 2026-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0003_remove_podcast_stats_podcast_metric_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='badge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='podcast',
            name='badge_colour',
            field=models.CharField(blank=True, help_text="Hex colour for the thumbnail badge, e.g. #2dbe9e. Leave blank to cycle the site's default palette.", max_length=7),
        ),
    ]
