# Generated by Django 6.1.1 on 2026-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0004_podcast_badge_podcast_badge_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this episode to the featured section on /insights (up to 3).'),
        ),
    ]
