# Generated by Django 6.1.1 on 2026-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='accent',
            field=models.CharField(blank=True, help_text='Hex ring/border colour, e.g. #2c8e85.', max_length=7),
        ),
        migrations.AddField(
            model_name='venture',
            name='border_gradient',
            field=models.CharField(blank=True, help_text='Full CSS radial-gradient(...) for the card border.', max_length=255),
        ),
    ]
