# Generated by Django 6.1.1 on 2026-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0002_venture_accent_venture_border_gradient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='accent',
            field=models.CharField(blank=True, help_text='Hex ring/border colour (e.g. #2c8e85 for teal, #a00017 for crimson, #2e21b6 for indigo).', max_length=7),
        ),
        migrations.AlterField(
            model_name='venture',
            name='border_gradient',
            field=models.CharField(blank=True, help_text='Full CSS radial-gradient(...) for the card border. Auto-populated when using theme presets in admin.', max_length=255),
        ),
        migrations.AlterField(
            model_name='venture',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the grid (0 to 8). Desktop places 5 on the top row, 4 on the second row.'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this venture from the public site without deleting it.'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='logo',
            field=models.ImageField(blank=True, help_text='Venture logo (recommended transparent PNG/WebP, max ~200x72px). If omitted, an empty grey plate is displayed.', null=True, upload_to='ventures/'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='name',
            field=models.CharField(help_text='Venture name (e.g. Merchanity, Abaad.pk).', max_length=150),
        ),
        migrations.AlterField(
            model_name='venture',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline or domain description (e.g. Digital Commerce Solutions).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='website_url',
            field=models.URLField(blank=True, help_text='External website URL (e.g. https://merchanity.com). Leave empty if site is not yet live.', null=True),
        ),
    ]
