# Generated by Django 6.1.1 on 2026-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_rename_text_testimonial_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Square profile photo. Recommended min 80x80px (.webp, .jpg, .png). If omitted, a colorful monogram avatar is displayed automatically.', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(help_text='The testimonial quote or feedback.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Determines card position in the masonry grid (0, 1, 2...).'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='handle',
            field=models.CharField(blank=True, help_text='Social handle (e.g. @username) or role/designation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this testimonial from the public site without deleting it.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Full name of the person giving the testimonial.', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='social_url',
            field=models.URLField(blank=True, help_text='Direct link to the original tweet, post, or reviewer profile.', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Keywords or hashtags. In admin, enter comma-separated values (e.g. dev, tools).'),
        ),
    ]
